sonar.projectKey=student-a_flight-catalog-service
sonar.organization=student-a-github-username
sonar.sources=.
sonar.exclusions=**/tests/**,**/venv/**,**/__pycache__/**
sonar.tests=tests/
sonar.python.version=3
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml